### ISSUE TITLE
Problem updating Sickrage within Docker on Synology

### ISSUE THREAD

**Issue by ronrosenfeld** [linuxserver/docker-sickbeard#11]
Not sure if this is a Docker or a Sickrage problem or a Synology problem.
I am running current versions of each, and this has been going on for a while, through multiple versions  of each.

Docker 17.05.0-0379
Accessing the Sickrage Web GUI via a Windows 10 computer on the LAN

If I select to update Sickrage from the GUI, Sickrage appears to shutdown and restart with the update satisfactorily.

However, Sickrage doesn't really work at that point with the Sickrage log showing repeated messages:

> 2018-09-19 07:07:58 INFO     MAIN :: Starting SickRage [master] using '/config/config.ini'
> 2018-09-19 07:07:58 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
> 2018-09-19 07:07:58 INFO     TORNADO :: Could not start webserver on port 8081: already in use!

which repeat ad infinitum.

To get out of this loop, I
 - Shut down Sickrage from the web GUI
 - Stop Sickrage in Docker on my Synology
 - ReStart Sickrage from Docker

Then, everything works OK.

Any thoughts to correct this annoyance would be appreciated.

**Comment by homerr** [comment]
Don't try and do updates through the sickrage ui, pull the latest from Docker and recreate the container so it runs the latest versions

**Comment by ronrosenfeld** [comment]
I'm pretty sure I'm getting the latest updates.  And it seems a lot simpler to do through the GUI than recreating a container.  Only for this port 8081 issue.

**Comment by sparklyballs** [comment]
the "issue" you're getting is solely because you're updating through the webui.

docker doesn't know that's what you are doing, the s6 init system just thinks the app has crashed and attempts to respawn it. but the port hasn't been released and sickrage crashes out because the port isn't available. 

in short, don't update through the webui.
