### ISSUE TITLE
Sickbeard init script throws error

### ISSUE THREAD

**Issue by alexdimitriou** [linuxserver/docker-sickbeard#5]
Starting up Sick Beard master
10:46:40 INFO::MAIN :: Checking database structure...
10:46:40 INFO::MAIN :: Database upgrade required: Initial Schema
10:46:40 ERROR::MAIN :: Your database version (44) has been incremented past what this version of Sick Beard supports (18).
If you have used other forks of Sick Beard, your database may be unusable due to their modifications.

[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)](https://linuxserver.io)

Ubuntu Server 16.04

**Comment by sparklyballs** [comment]
sounds like you tried using another branch and returning to this one.

**Comment by sparklyballs** [comment]
closing this, no feedback from user, suspect trying to use same appdata from another version of sickbeard.
