### ISSUE TITLE
BTN API

### ISSUE THREAD

**Issue by LG1990** [linuxserver/docker-sickbeard#6]
Hello,
can you please update Sickbeard so that it's compatible with the latest BTN Api's.
There is already a bufix
https://github.com/midgetspy/Sick-Beard/pull/982

Thank you

**Comment by CHBMB** [comment]
It will get rebuilt on Friday at about 23:00 UTC.  All our containers get updated weekly.

**Comment by sparklyballs** [comment]
not to mention there is no bugfix, at least not via that PR 

the PR is still open and hasn't been merged.

**Comment by LG1990** [comment]
Setting 
141.101.120.94 api.btnapps.net
in the host file should solve the issue! Could you update the docker one?

**Comment by CHBMB** [comment]
I personally don't favour that approach and think it would be far more sensible to encourage the fixing of this upstream. https://github.com/midgetspy/Sick-Beard/pull/984
